/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Check, Handshake, Search, XCircle } from 'lucide-react';
import { adminApi } from '../services/adminApi';
import { formatMoney, getApiErrorMessage, userSaleRequestStatusLabel } from '../services/apiUtils';
import type { UserSaleRequestDto } from '../types/commerce';

export default function AdminUserSaleRequests() {
  const [items, setItems] = useState<UserSaleRequestDto[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [search,setSearch]=useState(''); const [form,setForm]=useState({ acquisitionPrice:'', targetResalePrice:'', note:'' });
  const load=()=>{setLoading(true);adminApi.userSaleRequests({pageSize:100}).then(setItems).catch(e=>setError(getApiErrorMessage(e,'Alım talepleri yüklenemedi.'))).finally(()=>setLoading(false));}; useEffect(load,[]);
  const filtered=items.filter(i=>i.title.toLowerCase().includes(search.toLowerCase())||i.userId.toLowerCase().includes(search.toLowerCase()));
  const approve=async(id:string)=>{setSaving(true);try{await adminApi.approveUserSaleRequest(id,{acquisitionPrice:Number(form.acquisitionPrice||0),targetResalePrice:Number(form.targetResalePrice||0),adminNote:form.note||null});setMessage('Talep onaylandı. Ürün otomatik katalog/listing oluşturmaz.');load();}catch(e){setError(getApiErrorMessage(e,'Talep onaylanamadı.'));}finally{setSaving(false);}};
  const reject=async(id:string)=>{setSaving(true);try{await adminApi.rejectUserSaleRequest(id,form.note||'Admin tarafından reddedildi.');setMessage('Talep reddedildi.');load();}catch(e){setError(getApiErrorMessage(e,'Talep reddedilemedi.'));}finally{setSaving(false);}};
  const intake=async(id:string)=>{setSaving(true);try{await adminApi.intakeUserSaleRequest(id,form.note||'Fiziksel değerlendirme/intake sürecine alındı.');setMessage('Talep intake durumuna alındı; tek tık kataloglaştırma future scope.');load();}catch(e){setError(getApiErrorMessage(e,'Intake işlemi başarısız.'));}finally{setSaving(false);}};
  return <div><div className="page-header"><div><h1 className="page-title">Kullanıcıdan Ürün Alma</h1><p className="page-subtitle">Approve/reject/intake çalışır; otomatik Product/Item/Listing oluşturulmaz.</p></div></div>{error&&<div className="error-banner" style={{marginBottom:16}}>{error}</div>}{message&&<div style={{color:'#6ee7b7',marginBottom:16}}>{message}</div>}<div className="data-table-wrapper"><div className="data-table-header"><div className="search-bar" style={{minWidth:300}}><Search size={15}/><input placeholder="Talep ara..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{loading?<Empty text="Talepler yükleniyor..."/>:filtered.length===0?<Empty text="Talep bulunamadı."/>:<table className="data-table"><thead><tr><th>Talep</th><th>Kullanıcı</th><th>Tahmini Değer</th><th>Durum</th><th style={{textAlign:'right'}}>İşlem</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.title}</strong><div style={{color:'var(--text-muted)',fontSize:'0.78rem'}}>{r.description}</div></td><td>{r.userId}</td><td>{formatMoney(r.userEstimatedValue)}</td><td><span className="badge badge-purple">{userSaleRequestStatusLabel[String(r.status)]??String(r.status)}</span></td><td style={{textAlign:'right'}}><div style={{display:'flex',gap:8,justifyContent:'flex-end',flexWrap:'wrap'}}><button className="btn btn-ghost" disabled={saving} onClick={()=>approve(r.id)}><Check size={14}/> Onay</button><button className="btn btn-ghost" disabled={saving} onClick={()=>intake(r.id)}>Intake</button><button className="btn btn-ghost" disabled={saving} style={{color:'#f87171'}} onClick={()=>reject(r.id)}><XCircle size={14}/> Ret</button></div></td></tr>)}</tbody></table>}</div><div className="data-table-wrapper" style={{marginTop:18,padding:18}}><h3 style={{marginBottom:12}}>Admin işlem değerleri</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><input className="form-input" placeholder="Alım fiyatı" value={form.acquisitionPrice} onChange={e=>setForm(p=>({...p,acquisitionPrice:e.target.value}))}/><input className="form-input" placeholder="Hedef satış fiyatı" value={form.targetResalePrice} onChange={e=>setForm(p=>({...p,targetResalePrice:e.target.value}))}/><input className="form-input" placeholder="Admin notu / ret nedeni" value={form.note} onChange={e=>setForm(p=>({...p,note:e.target.value}))}/></div></div></div>;
}
function Empty({text}:{text:string}){return <div style={{padding:'60px 0',textAlign:'center',color:'var(--text-muted)'}}><Handshake size={32} style={{margin:'0 auto 12px',opacity:.3}}/><p>{text}</p></div>}
